echo "${{secrets.ENV_APP}}" > .env
echo "${{secrets.ENV_LOG}}" >> .env
echo "${{secrets.ENV_DB}}" >> .env
echo "${{secrets.ENV_SESSION}}" >> .env
echo "${{secrets.ENV_CACHE}}" >> .env
echo "${{secrets.ENV_REDIS}}" >> .env
echo "${{secrets.ENV_MAIL}}" >> .env
echo "${{secrets.ENV_AWS}}" >> .env
echo "${{secrets.ENV_HOST}}" >> .env
